<?php
$path_lib = implode( DIRECTORY_SEPARATOR ,array_slice(explode(DIRECTORY_SEPARATOR ,__DIR__),0,-3));
require_once $path_lib . '/lib/config.inc.php';
require_once $path_lib . '/lib/app.inc.php';
if (isset($app)) {
    //* Check permissions for module
    $app->auth->check_module_permissions('zabbix');

    // For module installation
    if(is_file($path_lib . '/web/zabbix/install.php')) include $path_lib . '/web/zabbix/install.php';

    return $app;
} else{
  die('Erreur load App file');
}

/*
EVENT.ACK.STATUS = {EVENT.ACK.STATUS}
EVENT.AGE = {EVENT.AGE}
EVENT.DATE = {EVENT.DATE}
EVENT.ID = {EVENT.ID}
EVENT.NAME = {EVENT.NAME}
EVENT.NSEVERITY = {EVENT.NSEVERITY}
EVENT.RECOVERY.DATE = {EVENT.RECOVERY.DATE}
EVENT.RECOVERY.ID = {EVENT.RECOVERY.ID}
EVENT.RECOVERY.NAME = {EVENT.RECOVERY.NAME}
EVENT.RECOVERY.STATUS = {EVENT.RECOVERY.STATUS}
EVENT.RECOVERY.TAGS = {EVENT.RECOVERY.TAGS}
EVENT.RECOVERY.TIME = {EVENT.RECOVERY.TIME}
EVENT.RECOVERY.VALUE = {EVENT.RECOVERY.VALUE}
EVENT.SEVERITY = {EVENT.SEVERITY}
EVENT.STATUS = {EVENT.STATUS}
EVENT.TAGS = {EVENT.TAGS}
EVENT.TIME = {EVENT.TIME}
EVENT.UPDATE.ACTION = {EVENT.UPDATE.ACTION}
EVENT.UPDATE.DATE = {EVENT.UPDATE.DATE}
EVENT.UPDATE.HISTORY = {EVENT.UPDATE.HISTORY}
EVENT.UPDATE.MESSAGE = {EVENT.UPDATE.MESSAGE}
EVENT.UPDATE.TIME = {EVENT.UPDATE.TIME}
EVENT.VALUE = {EVENT.VALUE}
*/
?>

