<?php

require_once '../../../lib/config.inc.php';
require_once '../../../lib/app.inc.php';

$app->auth->check_module_permissions('zabbix');

/*
EVENT.ACK.STATUS = {EVENT.ACK.STATUS}
EVENT.AGE = {EVENT.AGE}
EVENT.DATE = {EVENT.DATE}
EVENT.ID = {EVENT.ID}
EVENT.NAME = {EVENT.NAME}
EVENT.NSEVERITY = {EVENT.NSEVERITY}
EVENT.RECOVERY.DATE = {EVENT.RECOVERY.DATE}
EVENT.RECOVERY.ID = {EVENT.RECOVERY.ID}
EVENT.RECOVERY.NAME = {EVENT.RECOVERY.NAME}
EVENT.RECOVERY.STATUS = {EVENT.RECOVERY.STATUS}
EVENT.RECOVERY.TAGS = {EVENT.RECOVERY.TAGS}
EVENT.RECOVERY.TIME = {EVENT.RECOVERY.TIME}
EVENT.RECOVERY.VALUE = {EVENT.RECOVERY.VALUE}
EVENT.SEVERITY = {EVENT.SEVERITY}
EVENT.STATUS = {EVENT.STATUS}
EVENT.TAGS = {EVENT.TAGS}
EVENT.TIME = {EVENT.TIME}
EVENT.UPDATE.ACTION = {EVENT.UPDATE.ACTION}
EVENT.UPDATE.DATE = {EVENT.UPDATE.DATE}
EVENT.UPDATE.HISTORY = {EVENT.UPDATE.HISTORY}
EVENT.UPDATE.MESSAGE = {EVENT.UPDATE.MESSAGE}
EVENT.UPDATE.TIME = {EVENT.UPDATE.TIME}
EVENT.VALUE = {EVENT.VALUE}
*/
?>

